platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: goflake

outputs:
- name: coverage-results

run:
  path: ./goflake/concourse/scripts/build.sh
